[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "nodejs_18", "npm-9_x", "nginx", "libmysqlclient"]

[phases.build]
cmds = ["npm run prod", "php artisan optimize:clear", "php artisan storage:link"]

[start]
cmd = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"